### ISSUE TITLE
Support for transcluding same block multiple times.

### ISSUE THREAD

**Issue by kbaltrinic** [zachsnow/ng-multi-transclude#10]
It is possible to put multiple ng-transclude directives in the same template, in order to transclude the same elements more than once.  We use this to transclude the same set of action buttons into the top and bottom of a directive that produces a long page.

Trying to replicate this with ng-multi-transclude by including multiple ng-multi-transclude directives with the same value does not work in the same way.  What happens is that the trancluded block gets appended to the first location by the first ng-mutli-transclude directive.  When the second directive attempts to append the same block to a different location, the block gets removed from the original location.  This is happening because the same instance of the htmlElement DOM object that is being appended, and the same node cannot be attached to multiple locations in the DOM tree.

The difference is that ng-multi-transclude, due to the [test at Line 90](https://github.com/zachsnow/ng-multi-transclude/blob/master/src/multi-transclude.js#L90) only calls the angular $transclude function once per ng-multi-transclude-controller, in order to avoid re-linking scope.  This however, breaks the ability to re-transclude the same block as the append call does not get a new clone each time. 

I have confirmed this by disabling the if on line 90 and things work again.  Since I am not clear on negative impact of relinking to other use cases, I am not certain as to what the correct solution is.  Can you advise?

**Comment by zachsnow** [comment]
Maybe this works with AngularJS 1.5 and "multi-slot transclusion" -- in any event this library is now obsolete, see https://docs.angularjs.org/api/ng/directive/ngTransclude#multi-slot-transclusion
