### ISSUE TITLE
Directive with multi-transclude inside ng-form

### ISSUE THREAD

**Issue by dilyandimitrov** [zachsnow/ng-multi-transclude#18]
Hi,

I have a custom directive with 2 ng-multi-transclude divs. I put the directive in div with ng-form="myForm" element. Inside the directive I have some inputs (name="nameField") which I want to validate with the build-in validation from AngularJS. When I am trying to acces myForm.nameField.$error.required I got nothing - nameField is undefined. Do you have any idea is this related with multi-translude? I tried with the build-in transclude and it was fine.

**Comment by zachsnow** [comment]
Hey @dilyandimitrov, without seeing more code it's hard to say. It could be that you are running afoul of scoping issues (see https://github.com/zachsnow/ng-multi-transclude/issues/16 and possibly https://github.com/zachsnow/ng-multi-transclude/issues/8#issuecomment-53279421).

If you'd care to share your code via a plunkr I'm happy to have a look.

**Comment by dilyandimitrov** [comment]
Hi @zachsnow 
I made a plunkr for you with the problem I have - http://plnkr.co/edit/lb1zlOOShDonutHgY4vh?p=preview

**Comment by zachsnow** [comment]
Hey @dilyandimitrov it looks like the outer `form` controller is not available to the inner `input` directive; not sure why yet.

**Comment by zachsnow** [comment]
This should be fixed in `master`.

**Comment by dilyandimitrov** [comment]
Hey @zachsnow.
Are you sure that the latest change fixes my problem with the form validation. I tried on the given plnkr above and it not seems to work.
