### ISSUE TITLE
push package to npm

### ISSUE THREAD

**Issue by tuchk4** [zachsnow/ng-multi-transclude#32]

**Comment by okhomenko** [comment]
+1

**Comment by dmaslov** [comment]
+1 plz!

**Comment by mrkrstphr** [comment]
+1
Jumping through hoops right now to use this

**Comment by zachsnow** [comment]
Ok, I tried to do this but I've never had the need to publish to npm before so not sure if it's what you folks were looking for. If you have change you'd like me to make let me know or add a pull request or whatever. Cheers.

**Comment by mrkrstphr** [comment]
Looks gold to me
